### ISSUE TITLE
issue test 2

### ISSUE THREAD

**Issue by ruibaby** [guqing/halo#2]
### What is version of Halo has the issue?

none

### What database are you using?

MySQL 5.7

### Your site address.

https://halo.run

### What happened?

/assign @guqing

**Comment by ruibaby** [comment]
/*question

**Comment by guqing** [comment]
请到 [Halo Forum](https://bbs.halo.run/) 提问. 我们在那边有一个很好的社区. 他们已经回答了数千个问题，并且很乐意回答您的问题. 也可以到[Halo 官网](https://halo.run) 查看文档指南.
